-- =========================================================
-- Peraí, tem pudim! — schema inicial
-- =========================================================

create extension if not exists pgcrypto;

-- =========================================================
-- Produtos
-- =========================================================

create table public.products (
  id uuid primary key default gen_random_uuid(),

  name text not null,
  flavor text not null,
  variant text not null default 'normal',
  size_ml integer,
  weight_grams integer,

  description text,
  image_url text,

  price numeric(10, 2) not null default 0,
  promotional_price numeric(10, 2),

  is_active boolean not null default true,
  is_featured boolean not null default false,
  is_on_promotion boolean not null default false,

  available_for_ready_delivery boolean not null default false,
  available_for_scheduled_order boolean not null default true,

  sort_order integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint products_variant_check
    check (variant in ('normal', 'zero_lactose')),

  constraint products_price_check
    check (price >= 0),

  constraint products_promotional_price_check
    check (
      promotional_price is null
      or promotional_price >= 0
    )
);

-- =========================================================
-- Disponibilidade e estoque
-- =========================================================

create table public.product_availability (
  id uuid primary key default gen_random_uuid(),

  product_id uuid not null
    references public.products(id)
    on delete cascade,

  availability_date date not null default current_date,
  available_quantity integer not null default 0,
  reserved_quantity integer not null default 0,

  is_available boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint product_availability_unique
    unique (product_id, availability_date),

  constraint product_availability_quantity_check
    check (
      available_quantity >= 0
      and reserved_quantity >= 0
      and reserved_quantity <= available_quantity
    )
);

-- =========================================================
-- Configurações gerais da loja
-- =========================================================

create table public.store_settings (
  id uuid primary key default gen_random_uuid(),

  store_name text not null default 'Peraí, tem pudim!',
  whatsapp_number text,

  ready_delivery_enabled boolean not null default true,
  scheduled_orders_enabled boolean not null default true,
  promotion_enabled boolean not null default false,

  minimum_order_value numeric(10, 2),
  free_delivery_minimum_value numeric(10, 2),

  origin_address text,
  origin_latitude numeric(10, 7),
  origin_longitude numeric(10, 7),
  maximum_delivery_distance_km numeric(8, 2),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- Horários de atendimento
-- =========================================================

create table public.store_hours (
  id uuid primary key default gen_random_uuid(),

  weekday integer not null,
  is_open boolean not null default true,
  opening_time time,
  closing_time time,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint store_hours_weekday_check
    check (weekday between 0 and 6),

  constraint store_hours_unique_weekday
    unique (weekday),

  constraint store_hours_times_check
    check (
      is_open = false
      or (
        opening_time is not null
        and closing_time is not null
        and opening_time < closing_time
      )
    )
);

-- =========================================================
-- Faixas de entrega
-- =========================================================

create table public.delivery_ranges (
  id uuid primary key default gen_random_uuid(),

  max_distance_km numeric(8, 2) not null,
  fee numeric(10, 2) not null,

  is_active boolean not null default true,
  sort_order integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint delivery_ranges_distance_check
    check (max_distance_km > 0),

  constraint delivery_ranges_fee_check
    check (fee >= 0)
);

-- =========================================================
-- Pedidos
-- =========================================================

create table public.orders (
  id uuid primary key default gen_random_uuid(),

  order_number bigint generated by default as identity unique,

  customer_name text not null,
  customer_phone text not null,

  order_type text not null,
  fulfillment_type text not null,

  requested_date date,
  requested_time text,

  subtotal numeric(10, 2) not null default 0,
  delivery_fee numeric(10, 2) not null default 0,
  discount numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,

  distance_km numeric(8, 2),

  status text not null default 'pending',
  payment_status text not null default 'pending',
  payment_method text,

  customer_notes text,
  internal_notes text,

  whatsapp_opened_at timestamptz,
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint orders_order_type_check
    check (order_type in ('ready_delivery', 'scheduled')),

  constraint orders_fulfillment_type_check
    check (fulfillment_type in ('delivery', 'pickup')),

  constraint orders_status_check
    check (
      status in (
        'pending',
        'confirmed',
        'preparing',
        'ready',
        'out_for_delivery',
        'completed',
        'cancelled'
      )
    ),

  constraint orders_payment_status_check
    check (
      payment_status in (
        'pending',
        'paid',
        'refunded',
        'cancelled'
      )
    ),

  constraint orders_values_check
    check (
      subtotal >= 0
      and delivery_fee >= 0
      and discount >= 0
      and total >= 0
    )
);

-- =========================================================
-- Itens dos pedidos
-- =========================================================

create table public.order_items (
  id uuid primary key default gen_random_uuid(),

  order_id uuid not null
    references public.orders(id)
    on delete cascade,

  product_id uuid
    references public.products(id)
    on delete set null,

  product_name text not null,
  product_flavor text,
  product_variant text,
  product_size_ml integer,
  product_weight_grams integer,

  quantity integer not null,
  unit_price numeric(10, 2) not null,
  total_price numeric(10, 2) not null,

  created_at timestamptz not null default now(),

  constraint order_items_quantity_check
    check (quantity > 0),

  constraint order_items_values_check
    check (
      unit_price >= 0
      and total_price >= 0
    )
);

-- =========================================================
-- Endereço de entrega
-- =========================================================

create table public.delivery_addresses (
  id uuid primary key default gen_random_uuid(),

  order_id uuid not null unique
    references public.orders(id)
    on delete cascade,

  postal_code text,
  street text not null,
  number text not null,
  complement text,
  neighborhood text not null,
  city text not null default 'Goiânia',
  state text not null default 'GO',
  reference text,

  latitude numeric(10, 7),
  longitude numeric(10, 7),

  created_at timestamptz not null default now()
);

-- =========================================================
-- Índices
-- =========================================================

create index products_active_sort_idx
  on public.products (is_active, sort_order);

create index product_availability_date_idx
  on public.product_availability (availability_date);

create index orders_created_at_idx
  on public.orders (created_at desc);

create index orders_status_idx
  on public.orders (status);

create index orders_requested_date_idx
  on public.orders (requested_date);

create index order_items_order_id_idx
  on public.order_items (order_id);

-- =========================================================
-- updated_at automático
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger product_availability_set_updated_at
before update on public.product_availability
for each row execute function public.set_updated_at();

create trigger store_settings_set_updated_at
before update on public.store_settings
for each row execute function public.set_updated_at();

create trigger store_hours_set_updated_at
before update on public.store_hours
for each row execute function public.set_updated_at();

create trigger delivery_ranges_set_updated_at
before update on public.delivery_ranges
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- =========================================================
-- RLS
-- =========================================================

alter table public.products enable row level security;
alter table public.product_availability enable row level security;
alter table public.store_settings enable row level security;
alter table public.store_hours enable row level security;
alter table public.delivery_ranges enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_addresses enable row level security;

-- Leitura pública apenas do que o app público precisa.

create policy "Public can read active products"
on public.products
for select
to anon, authenticated
using (is_active = true);

create policy "Public can read product availability"
on public.product_availability
for select
to anon, authenticated
using (is_available = true);

create policy "Public can read store settings"
on public.store_settings
for select
to anon, authenticated
using (true);

create policy "Public can read store hours"
on public.store_hours
for select
to anon, authenticated
using (true);

create policy "Public can read active delivery ranges"
on public.delivery_ranges
for select
to anon, authenticated
using (is_active = true);

-- Por enquanto, nenhuma escrita pública é permitida.
-- Pedidos serão criados posteriormente por uma função segura.

-- =========================================================
-- Dados iniciais
-- =========================================================

insert into public.store_settings (
  store_name,
  ready_delivery_enabled,
  scheduled_orders_enabled,
  promotion_enabled,
  maximum_delivery_distance_km
)
values (
  'Peraí, tem pudim!',
  true,
  true,
  false,
  12
);

insert into public.store_hours (
  weekday,
  is_open,
  opening_time,
  closing_time
)
values
  (0, false, null, null),
  (1, true, '10:00', '20:00'),
  (2, true, '18:00', '20:00'),
  (3, true, '10:00', '20:00'),
  (4, true, '18:00', '20:00'),
  (5, true, '09:00', '18:00'),
  (6, true, '09:00', '14:00');

insert into public.delivery_ranges (
  max_distance_km,
  fee,
  sort_order
)
values
  (3, 6, 1),
  (6, 8, 2),
  (9, 11, 3),
  (12, 15, 4);